spring.datasource.url=jdbc:postgresql://ep-gentle-band-ap75m97m-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YkcMO98IjEzZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=library-backend
spring.jpa.show-sql=false
